[package]
name = "rust-solution-01"
version = "0.1.0"
authors = ["Jess Bowers <jessbowers@me.com>"]
edition = "2018"

[dependencies]
derive_more = "0.99.11"
clap = {version = "2.34", features = ["yaml"]}
anyhow = "1.0.45"
